version: "3"
services: 
  mongo:
    container_name: mongo-container-course
    image: mongo
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-container-course
    build: .
    restart: always
    image: clean-node-api
    command: npm run debug
    volumes: 
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"      
    links:
      - mongo
    environment: 
      - MONGO_URL=mongodb://mongo:27017/clean-node-api